### PR TITLE
Preparation to pushlish on PyPI

### PR DESCRIPTION
**Pull request by fabaff**
To be able to pushlish `arjun` on PyPI it's required to have a different structure.

The changes in detail:

- Make it a package (move to `arjun`)
- Move parts out of `__main__.py` (former `arjun.py`)
- Add setup.py file and allow to run the tool with `arjun` instead of `python3 arjun.py ...`
- Add setup.cfg file
- Start to collect contants at one location
- Update README
- Fix typos in README
- Follow PEP8 (with `black`) and PEP257

### CODE REVIEW

**Comment by s0md3v** [comment]
Thanks for submitting the pull request but I have no plans of uploading it to pypi.
I feel bad that you had to work on it and I am sorry for the same.
Thanks again.

**Comment by fabaff** [comment]
Yeah, that's the reason why I added myself as maintainer for PyPI.

Providing a `setup.py` file is how Python tools are handled in an easy way by users and when it comes to packaging tools for distributions. In the current state all future package maintainers have to jump to hoops.

**Comment by s0md3v** [comment]
Hi @fabaff ,

Resolve the conflicts and we are ready to merge.
Sorry for the inconvenience.

Thanks for the contribution.

**Comment by fabaff** [comment]
What's the hold-up? I fixed the conflicts two months ago and now there are again some...

**Comment by fabaff** [comment]
Why was this closed?

**Comment by fabaff** [comment]
This is now blocking the inclusion of osmedeus into the Fedora Package Collection...

**Pull request closed without merging**
