### PR TITLE
Options handling string 

### PR DESCRIPTION
**Pull request by alanEG**
Hello
### Description 
I add 3 options `-ps` `-ms` `mr`
- ##### The first Option `-ps`
Add user input in parameter value And also You should add `{random}` tag in argument 
Because the program will replace this value to random integer value
- ##### The second option `-ms`
This option take a value from user then check if this value in response or not 
Also you can add multiple value like `-ms value,value2`
- ##### The second option `-mr`
This options like `-ms` put it take regex 
### How to test 
- ##### -ps
`arjun -u https://example.com/file -w file -ps "<script>test{random}test</script>"`
- ##### -ms
`arjun -u https://example.com/file -w file -ms "String"`
- ##### -mr
`arjun -u https://example.com/file -w file -mr "[a-zA-Z0-9]"`

### CODE REVIEW

**Comment by s0md3v** [comment]
Hi @alanEG,

Thanks for MR!
However, I am not sure how these options can help in parameter discovery. Can you please elaborate?

**Comment by alanEG** [comment]
Hello @s0md3v 
You can use theses options for many reasons  
Like
Also You can use -pt for add some bad characters for make the application return something 
Also because something you work in dynamic application Sometime in this case you need to match a specific value -mc -ms and -mr will help you

**Comment by s0md3v** [comment]
Thanks for clearing that up @alanEG but I still don't understand the purpose of matching a specific value. How will that help in detecting valid parameters? Can you describe such a common case?

**Comment by alanEG** [comment]
Let's say we have dynamic website this website print random value in the content or print a value of any parameter in the content of website 
In  this case we will receive not valid results in this you need to match specific word or string you can use `-ps` and `-ms` together for match value we add in `-ps`
Example:
`https://www.example.com/test?ioasdfkasdf=test&test"'`
The content will be 
```
<html>
<body>
<link src="https://www.example.com/test%3Fioasdfkasdf%3Dtest%26test%3D%22%27"></link>
</body>
<html>
```
Because that we need to use `-ps` and `-ms` or `-mr` for match the valid parameter 

Example:
`https://www.example.com/test?ioasdfkasdf=test&test"'&content=<h1>{random}</h1>`
The content will be 
```
<html>
<body>
<link src="https://www.example.com/test%3Fioasdfkasdf%3Dtest%26test%3D%22%27"><h1>{random}</h1></link>
</body>
<html>
```
Also 
I have create this MR because this case 
We have website has SQL injection vulnerability in some parameter 
But this website return a one response for all parameter value but if there exceptions in sql query the website will return 200 Status code and specific content the match content and put string will be good in this case and more specific
 
Maybe the match-string and match-regex argument will be not useful alone 
But they will be useful with put-string

**Comment by s0md3v** [comment]
1. "In this case we will receive not valid results" - we will. Arjun can handle dynamic content.
2. Arjun's objective is to find parameters, nothing more, nothing less.

Apologies for rejecting your MR, I appreciate your hard work but your changes don't align with Arjun.

**Pull request closed without merging**
